---
- hosts: all
  become: true
  tasks:
  - name: Install Apache
    command: yum install -y httpd httpd-devel
  - name: copy configuration files--example1.conf
    copy:
            src: "/home/ansadmin/appconfig/example1/example1.conf"
            dest: "/etc/httpd/conf.d"
  - name: copy configuration files--example2.conf
    copy:
            src: "/home/ansadmin/appconfig/example2/example2.conf"
            dest: "/etc/httpd/conf.d"
  - name: Directories for website 
    raw:
       mkdir -p /var/www/html/example1
       mkdir -p /var/www/html/example2
  - name: Copy index.html files --example1
    copy:
       src: "/home/ansadmin/appconfig/example1/index.html"
       dest: "/var/www/html/example1/"
  - name: Copy index.html files --example2
    copy:
       src: "/home/ansadmin/appconfig/example2/index.html"
       dest: "/var/www/html/example2/"

  - name: Make sure Apache is started and configure it to run at boot.
    service: name=httpd state=started enabled=yes

  - name: Update /etc/hosts file
    raw:
        echo "hello world"
    #172.31.74.119 www.example1.com
    #172.31.74.119 www.example2.com
    #curl www.example1.com
    #curl www.example2.com

